server:
  port: $PORT
pingtask:
  url: https://www.google.com
  period: 1200000
telegrambot:
  webHookPath: ${WEBHOOK_PATH}
  userName: ${BOT_NAME}
  botToken: ${BOT_TOKEN}
apisearch:
  apiToken: ${GS_API_TOKEN}
  context: ${GS_API_CS}